### ISSUE TITLE
[BUG] Safari doesn't render list-group-items for smarttable

### ISSUE THREAD

**Issue by nerdgrass** [chimera/tubbsfireinfo.com#2]
## Problem
SmartTable components are not rendering in Safari or Mobile Safari.

## Investigation
Repro'd issue easily enough in production, but could not reproduce `ReferenceError: Can't find variable: React` error seen in live version safari. Unsure how, but Safari isn't able to load React, which causes tables to not load into their appropriate elements. Still investigating

**Comment by nerdgrass** [comment]
I need to get back to my work, I'll take another stab at this in a couple hours.

**Comment by danawoodman** [comment]
Fixed last night!

**Comment by danawoodman** [comment]
e
